// Code generated by wit-bindgen-go. DO NOT EDIT.

package childapi

import (
	"example.com/hellokubernetes/wasm-operator/operator/http"
	"example.com/hellokubernetes/wasm-operator/operator/types"
)

// This file contains wasmimport and wasmexport declarations for "wasm-operator:operator".

//go:wasmexport wasm-operator:operator/child-api#handle-response
//export wasm-operator:operator/child-api#handle-response
func wasmexport_HandleResponse(id0 uint64, res0 uint32, res1 *http.Header, res2 uint32, res3 *uint8, res4 uint32) {
	id := (types.AsyncID)((uint64)(id0))
	res := lift_Response((uint32)(res0), (*http.Header)(res1), (uint32)(res2), (*uint8)(res3), (uint32)(res4))
	Exports.HandleResponse(id, res)
	return
}
