// Code generated by wit-bindgen-go. DO NOT EDIT.

package parentapi

import (
	"example.com/hellokubernetes/wasm-operator/operator/http"
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wasm-operator:operator".

//go:wasmimport wasm-operator:operator/parent-api send-request
//go:noescape
func wasmimport_SendRequest(req0 uint32, req1 *uint8, req2 uint32, req3 *http.Header, req4 uint32, req5 *uint8, req6 uint32, result *cm.Result[string, AsyncID, string])
