[package]
name = "ring-operator-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", tag = "v0.26.0" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.142"

[lib]
crate-type = ["cdylib"]