// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "wasm-operator:operator/types".
package types

// AsyncID represents the u64 "wasm-operator:operator/types#async-id".
//
//	type async-id = u64
type AsyncID uint64
