apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: [ "sleep", "3600" ]
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"
        limits:
          memory: "20Mi"
          cpu: "20m"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: [ "sleep", "3600" ]
      resources:
        requests:
          memory: "10Mi"
          cpu: "10m"
        limits:
          memory: "20Mi"
          cpu: "20m"