// Code generated by wit-bindgen-go. DO NOT EDIT.

package terminaloutput

// This file contains wasmimport and wasmexport declarations for "wasi:cli@0.2.6".

//go:wasmimport wasi:cli/terminal-output@0.2.6 [resource-drop]terminal-output
//go:noescape
func wasmimport_TerminalOutputResourceDrop(self0 uint32)
