// Code generated by wit-bindgen-go. DO NOT EDIT.

package parentapi

import (
	"go.bytecodealliance.org/cm"
	"hellokubernetes/internal/wasm-operator/operator/http"
)

func lower_Request(v http.Request) (f0 uint32, f1 *uint8, f2 uint32, f3 *http.Header, f4 uint32, f5 *uint8, f6 uint32) {
	f0 = (uint32)(v.Method)
	f1, f2 = cm.LowerString(v.URI)
	f3, f4 = cm.LowerList(v.Headers)
	f5, f6 = cm.LowerList(v.Body)
	return
}
