// Code generated by wit-bindgen-go. DO NOT EDIT.

package parentapi

import (
	"go.bytecodealliance.org/cm"
	k8shttp "hellokubernetes/internal/wasm-operator/operator/k8s-http"
	"unsafe"
)

// ResponseShape is used for storage in variant or result types.
type ResponseShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Response{})]byte
}

func lower_Request(v k8shttp.Request) (f0 uint32, f1 *uint8, f2 uint32, f3 *k8shttp.Header, f4 uint32, f5 *uint8, f6 uint32) {
	f0 = (uint32)(v.Method)
	f1, f2 = cm.LowerString(v.URI)
	f3, f4 = cm.LowerList(v.Headers)
	f5, f6 = cm.LowerList(v.Body)
	return
}
