// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package parentapi represents the imported interface "wasm-operator:operator/parent-api".
package parentapi

import (
	"go.bytecodealliance.org/cm"
	"hellokubernetes/internal/wasm-operator/operator/http"
	"hellokubernetes/internal/wasm-operator/operator/types"
)

// Request represents the type alias "wasm-operator:operator/parent-api#request".
//
// See [http.Request] for more information.
type Request = http.Request

// AsyncID represents the type alias "wasm-operator:operator/parent-api#async-id".
//
// See [types.AsyncID] for more information.
type AsyncID = types.AsyncID

// SendRequest represents the imported function "send-request".
//
//	send-request: func(req: request) -> result<async-id, string>
//
//go:nosplit
func SendRequest(req Request) (result cm.Result[string, AsyncID, string]) {
	req0, req1, req2, req3, req4, req5, req6 := lower_Request(req)
	wasmimport_SendRequest((uint32)(req0), (*uint8)(req1), (uint32)(req2), (*http.Header)(req3), (uint32)(req4), (*uint8)(req5), (uint32)(req6), &result)
	return
}
