// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package operator represents the world "wasm-operator:operator/operator".
//
// The wasip2 target of TinyGo assumes that the component is targeting
// wasi:cli/command@0.2.0 world (part of wasi:cli) so it requires the imports of wasi:cli/imports@0.2.0
package operator
