// Code generated by wit-bindgen-go. DO NOT EDIT.

package childapi

import (
	"go.bytecodealliance.org/cm"
	"hellokubernetes/internal/wasm-operator/operator/http"
)

func lift_Response(f0 uint32, f1 *http.Header, f2 uint32, f3 *uint8, f4 uint32) (v http.Response) {
	v.Status = (uint16)(f0)
	v.Headers = cm.LiftList[cm.List[http.Header]](f1, f2)
	v.Body = cm.LiftList[cm.List[uint8]](f3, f4)
	return
}
