// Code generated by wit-bindgen-go. DO NOT EDIT.

package childapi

// Exports represents the caller-defined exports from "wasm-operator:operator/child-api".
var Exports struct {
	// Start represents the caller-defined, exported function "start".
	//
	//	start: func()
	Start func()
}
