// Code generated by wit-bindgen-go. DO NOT EDIT.

package childapi

// This file contains wasmimport and wasmexport declarations for "wasm-operator:operator".

//go:wasmexport wasm-operator:operator/child-api#start
//export wasm-operator:operator/child-api#start
func wasmexport_Start() {
	Exports.Start()
	return
}
