[package]
name = "parent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
serde = "1.0"
serde_yml = "0.0.12"
tokio = { version = "1.44.2", features=["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
wasmtime = "32.0.0"
wasmtime-wasi = "32.0.0"
