package local:operator@0.2.0;

interface kubernetes {
  use types.{log-level};
  log: func(level: log-level, message: string);
  get-resource: func(kind: string, name: string, namespace: string) -> result<string, string>;
  create-resource: func(kind: string, namespace: string, resource-json: string) -> result<_, string>;
  update-resource: func(kind: string, name: string, namespace: string, resource-json: string) -> result<_, string>;
  delete-resource: func(kind: string, name: string, namespace: string) -> result<_, string>;
}