package wasm-operator:operator;

interface k8s-http {
    enum method {
        get,
        post,
        put,
        delete,
        patch,
    }

    record header {
        name: string,
        value: string,
    }

    record request {
        method: method,
        uri: string,
        headers: list<header>,
        body: list<u8>, // Body as raw bytes
    }

    record response {
        body: list<u8>, // Body as raw bytes
    }
}


interface parent-api {
    use k8s-http.{request, response};

    resource future-response {
        get: func() -> result<response, string>;
    }

    send-request: func(req: request) -> result<future-response, string>;
}

interface child-api {
    start: func();
}

world operator {
    include wasi:cli/imports@0.2.6;

    import parent-api;
    export child-api;
}
